'use client';
import { FormEvent, useEffect, useState } from 'react';
import { supabase, SuccessStory } from '../../lib/supabase';

const emptyForm={title:'',description:'',thread_url:'',views:0,likes:0,comments:0,sort_order:0,is_published:true};

export default function AdminPage(){
  const [session,setSession]=useState<any>(null);const [stories,setStories]=useState<SuccessStory[]>([]);const [form,setForm]=useState(emptyForm);const [image,setImage]=useState<File|null>(null);const [editing,setEditing]=useState<SuccessStory|null>(null);const [email,setEmail]=useState('a0109460292@gmail.com');const [password,setPassword]=useState('');const [newPassword,setNewPassword]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[]);
  useEffect(()=>{if(session)loadStories()},[session]);
  const isAdmin=session?.user?.app_metadata?.role==='admin';
  async function loadStories(){const {data,error}=await supabase.from('success_stories').select('*').order('sort_order').order('created_at',{ascending:false});if(error)setMessage(error.message);else setStories(data||[])}
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');const {error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password:password.trim()});setMessage(error?'이메일 또는 비밀번호가 일치하지 않습니다. 다시 입력해주세요.':'로그인되었습니다.');setBusy(false)}
  async function save(e:FormEvent){e.preventDefault();if(!session||!isAdmin)return;setBusy(true);setMessage('');try{let imageUrl=editing?.image_url||'';if(image){const ext=image.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await supabase.storage.from('success-stories').upload(path,image,{contentType:image.type,upsert:false});if(uploadError)throw uploadError;imageUrl=supabase.storage.from('success-stories').getPublicUrl(path).data.publicUrl}if(!imageUrl)throw new Error('캡처 이미지를 선택해주세요.');const payload={...form,user_id:session.user.id,image_url:imageUrl};const result=editing?await supabase.from('success_stories').update(payload).eq('id',editing.id):await supabase.from('success_stories').insert(payload);if(result.error)throw result.error;setForm(emptyForm);setImage(null);setEditing(null);setMessage('저장되었습니다.');await loadStories()}catch(error:any){setMessage(error.message||'저장하지 못했습니다.')}finally{setBusy(false)}}
  function edit(story:SuccessStory){setEditing(story);setForm({title:story.title,description:story.description,thread_url:story.thread_url,views:story.views,likes:story.likes,comments:story.comments,sort_order:story.sort_order,is_published:story.is_published});setImage(null);window.scrollTo({top:0,behavior:'smooth'})}
  async function remove(story:SuccessStory){if(!confirm('이 성공 사례를 삭제할까요?'))return;const {error}=await supabase.from('success_stories').delete().eq('id',story.id);setMessage(error?error.message:'삭제되었습니다.');if(!error)loadStories()}
  async function changePassword(e:FormEvent){e.preventDefault();if(newPassword.length<8){setMessage('새 비밀번호는 8자 이상 입력해주세요.');return}const {error}=await supabase.auth.updateUser({password:newPassword});setMessage(error?error.message:'비밀번호가 변경되었습니다.');if(!error)setNewPassword('')}
  if(!session)return <main className="admin-page"><section className="admin-login"><a href="/" className="admin-back">← 브랜딩 페이지</a><p className="eyebrow">DYNA ADMIN</p><h1>성공 사례 관리</h1><p>관리자 계정으로 로그인해주세요.</p><form onSubmit={login}><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy}>{busy?'확인 중…':'로그인'}</button></form>{message&&<p className="admin-message">{message}</p>}</section></main>;
  if(!isAdmin)return <main className="admin-page"><section className="admin-login"><h1>접근 권한이 없습니다</h1><button onClick={()=>supabase.auth.signOut()}>로그아웃</button></section></main>;
  return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">DYNA ADMIN</p><h1>성공 사례 관리</h1></div><div><a href="/" target="_blank">사이트 보기 ↗</a><button onClick={()=>supabase.auth.signOut()}>로그아웃</button></div></header><div className="admin-layout"><section className="admin-editor"><h2>{editing?'콘텐츠 수정':'새 콘텐츠 등록'}</h2><form onSubmit={save}><label>게시글 캡처 이미지<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setImage(e.target.files?.[0]||null)} required={!editing}/></label><label>콘텐츠 제목<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required placeholder="예: 고객 질문에서 시작한 정보형 콘텐츠"/></label><label>성과 설명<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={4} placeholder="반응이 좋았던 이유를 짧게 적어주세요."/></label><label>실제 스레드 게시글 URL<input type="url" value={form.thread_url} onChange={e=>setForm({...form,thread_url:e.target.value})} placeholder="https://www.threads.net/..."/></label><div className="admin-numbers"><label>조회수<input type="number" min="0" value={form.views} onChange={e=>setForm({...form,views:Number(e.target.value)})}/></label><label>좋아요<input type="number" min="0" value={form.likes} onChange={e=>setForm({...form,likes:Number(e.target.value)})}/></label><label>댓글<input type="number" min="0" value={form.comments} onChange={e=>setForm({...form,comments:Number(e.target.value)})}/></label><label>노출 순서<input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label></div><label className="admin-check"><input type="checkbox" checked={form.is_published} onChange={e=>setForm({...form,is_published:e.target.checked})}/>사이트에 공개하기</label><div className="admin-actions"><button disabled={busy}>{busy?'저장 중…':editing?'수정 저장':'등록하기'}</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setForm(emptyForm);setImage(null)}}>취소</button>}</div></form>{message&&<p className="admin-message">{message}</p>}<form className="password-form" onSubmit={changePassword}><h3>관리자 비밀번호 변경</h3><label>새 비밀번호<input type="password" minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="8자 이상"/></label><button type="submit">비밀번호 변경</button></form></section><section className="admin-list"><h2>등록된 콘텐츠 <span>{stories.length}</span></h2>{stories.length===0?<p className="admin-empty">아직 등록된 콘텐츠가 없습니다.</p>:stories.map(story=><article key={story.id}><img src={story.image_url} alt=""/><div><div className="admin-status">{story.is_published?'공개':'비공개'} · 순서 {story.sort_order}</div><h3>{story.title}</h3><p>조회 {story.views.toLocaleString()} · 좋아요 {story.likes.toLocaleString()} · 댓글 {story.comments.toLocaleString()}</p><div className="admin-item-actions"><button onClick={()=>edit(story)}>수정</button><button onClick={()=>remove(story)}>삭제</button></div></div></article>)}</section></div></main>}
