'use client';
import { FormEvent, MouseEvent, useEffect, useState } from 'react';
type Product = { id: string; name: string; note: string; imageUrl: string; productUrl: string; tag: string };
const starterProducts: Product[] = [
  { id:'1', name:'하루를 가볍게 여는 생활템', note:'매일 손이 가는 실용적인 아이템', imageUrl:'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=900&q=80', productUrl:'#', tag:'오늘의 추천' },
  { id:'2', name:'집중력을 채워주는 데스크템', note:'일하는 시간을 산뜻하게 바꿔요', imageUrl:'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=900&q=80', productUrl:'#', tag:'가치픽' },
];
const profileLinks = [
  { icon:'📗', label:'스레드 무료 전자책', note:'스레드를 시작하고 성장시키는 실전 내용', cls:'mint', href:'https://app.notion.com/p/gachi-toktok-ebook/3bbadc431d3380e4a848d5f466747ff2?v=2ebdb0e27e4d4fb8bb354e27c62829af&source=copy_link' },
  { icon:'✍️', label:'스레드 마케팅 대행', note:'콘텐츠 기획과 운영·협업 방식 안내', cls:'lemon', href:'https://blog.naver.com/twobinsliving/224342440500' },
  { icon:'💬', label:'무료상담 및 협업 문의', note:'스레드 마케팅·브랜드 콘텐츠·위탁판매 협업', cls:'peach', href:'https://open.kakao.com/me/gachi_toktok' },
];
const expertise = [
  { number:'01', title:'스레드 마케팅', text:'브랜드의 목소리를 찾고, 팔로우하고 싶은 콘텐츠와 꾸준히 소통하는 계정을 설계합니다.' },
  { number:'02', title:'AI 콘텐츠 활용', text:'AI를 생각을 정리하고 콘텐츠 실행 속도를 높이는 실무 파트너로 활용합니다.' },
  { number:'03', title:'브랜드 메시지 설계', text:'상품의 기능을 나열하는 대신, 고객이 관심을 가져야 할 이유를 선명한 언어로 정리합니다.' },
  { number:'04', title:'온라인 쇼핑몰 운영', text:'스마트스토어와 쿠팡 등 실제 판매 채널의 관점에서 콘텐츠와 상품을 연결합니다.' },
];
export default function Home() {
  const [products,setProducts]=useState<Product[]>(starterProducts); const [editing,setEditing]=useState(false); const [saved,setSaved]=useState(false);
  const [form,setForm]=useState({name:'',note:'',imageUrl:'',productUrl:'',tag:'가치픽'}); const [cursor,setCursor]=useState({x:-50,y:-50}); const [particles,setParticles]=useState<{id:number;x:number;y:number}[]>([]);
  useEffect(()=>{ const stored=localStorage.getItem('value-smart-products'); if(stored){try{setProducts(JSON.parse(stored))}catch{}} const move=(e:globalThis.MouseEvent)=>setCursor({x:e.clientX,y:e.clientY}); window.addEventListener('mousemove',move); return()=>window.removeEventListener('mousemove',move)},[]);
  const burst=(e:MouseEvent<HTMLElement>)=>{const next=Array.from({length:7},(_,i)=>({id:Date.now()+i,x:e.clientX,y:e.clientY}));setParticles(v=>[...v,...next]);setTimeout(()=>setParticles(v=>v.filter(p=>!next.some(n=>n.id===p.id))),700)};
  const addProduct=(e:FormEvent)=>{e.preventDefault();const next=[{...form,id:crypto.randomUUID()},...products];setProducts(next);localStorage.setItem('value-smart-products',JSON.stringify(next));setForm({name:'',note:'',imageUrl:'',productUrl:'',tag:'가치픽'});setSaved(true);setTimeout(()=>setSaved(false),1800)};
  const removeProduct=(id:string)=>{const next=products.filter(p=>p.id!==id);setProducts(next);localStorage.setItem('value-smart-products',JSON.stringify(next))};
  return <main onClick={burst}>
    <div className="custom-cursor" style={{transform:`translate(${cursor.x}px, ${cursor.y}px)`}}><span>똑</span></div>{particles.map((p,i)=><i key={p.id} className="particle" style={{left:p.x,top:p.y,'--angle':`${i*51}deg`} as React.CSSProperties}/>)}
    <div className="sun sun-one"/><div className="sun sun-two"/><div className="doodle one">✦</div><div className="doodle two">⌁</div><button className="edit-toggle" onClick={()=>setEditing(!editing)}>{editing?'닫기 ×':'상품 관리 +'}</button>
    <section className="profile-card"><div className="profile-mark">가치<br/>똑똑<span>!</span></div><p className="eyebrow">HOME SHOPPING EXPERIENCE · CONTENT · COMMERCE</p><h1>좋은 가치를 발견해,<br/><em>선택받는 브랜드</em>로 만듭니다.</h1><p className="intro intro-lead">홈쇼핑에서 배운 ‘선택받는 법’을<br/>스레드 콘텐츠와 온라인 판매에 연결하는 마케터</p><div className="identity-chips"><span>스레드 마케팅</span><span>AI 콘텐츠</span><span>브랜드 메시지</span><span>온라인 쇼핑몰</span></div><p className="intro intro-story">약 12년간 홈쇼핑 채널을 운영하며 쌓은 경험을 바탕으로 브랜드와 상품의 강점을 <strong>고객이 반응하는 콘텐츠</strong>로 바꿉니다. 좋은 가치가 더 많은 사람에게 발견되고 실제 선택으로 이어지도록 돕습니다.</p><div className="link-stack">{profileLinks.map(l=><a key={l.label} className={`main-link ${l.cls}`} href={l.href} target="_blank" rel="noreferrer"><span className="link-icon">{l.icon}</span><span><strong>{l.label}</strong><small>{l.note}</small></span><b>↗</b></a>)}</div></section>
    <section className="expertise"><div className="section-title"><p className="section-kicker">WHAT I DO</p><h2>콘텐츠에서 판매까지,<br/>하나의 흐름으로 설계합니다</h2></div><div className="expertise-grid">{expertise.map(item=><article key={item.number}><span>{item.number}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
    <section className="about-note"><p className="section-kicker">VALUE SMART PHILOSOPHY</p><h2>잘 보이게 만드는 것을 넘어,<br/>제대로 선택받게</h2><p>좋은 상품도 고객이 그 가치를 이해하지 못하면 선택받기 어렵습니다. 가치똑똑은 눈에 띄는 포장에 머물지 않고 브랜드와 상품의 본질을 발견해 고객의 언어로 설명하고, 콘텐츠와 판매 채널까지 자연스럽게 연결합니다.</p><strong>좋은 가치를 알아보고, 똑똑하게 알리고, 오래 사랑받게 합니다.</strong></section>
    <section className="experience"><div className="experience-badge"><strong>12</strong><span>YEARS<br/>EXPERIENCE</span></div><div><p className="section-kicker">WHY VALUE SMART</p><h2>고객의 선택이 만들어지는<br/>현장을 이해합니다</h2><p>홈쇼핑 현장에서 약 12년 동안 상품이 소개되고 고객의 선택을 받는 과정을 가까이에서 경험했습니다. 무엇을 말할지뿐 아니라 어떻게 보여주고, 어떤 순서로 설명하며, 고객의 반응을 다음 전략에 반영할지를 알고 있습니다.</p></div></section>
    <section className="shop-preview"><p className="section-kicker">VALUE SHOP</p><h2>직접 고르고 판매하며<br/>확인한 상품들</h2><p className="section-copy">스마트스토어와 쿠팡을 직접 운영하며 고객의 선택과 온라인 판매의 흐름을 함께 경험합니다.</p><div className="shop-grid"><a href="https://smartstore.naver.com/dynaliving" target="_blank" rel="noreferrer"><small>NAVER</small>스마트스토어 <span>→</span></a><a href="https://shop.coupang.com/dynaliving?platform=p" target="_blank" rel="noreferrer"><small>COUPANG</small>쿠팡 마이샵 <span>→</span></a></div></section>
    <section className="recommendations"><div className="section-head"><div><p className="section-kicker">SMART PICKS</p><h2>가치똑똑의 기준으로<br/>고른 추천 아이템</h2></div><span>{products.length}개의 추천 아이템</span></div><div className="product-grid">{products.map(p=><article className="product" key={p.id}><a href={p.productUrl} target="_blank" rel="noreferrer"><div className="product-image"><img src={p.imageUrl} alt={p.name}/><span>{p.tag}</span></div><div className="product-copy"><h3>{p.name}</h3><p>{p.note}</p><b>상품 보러가기 ↗</b></div></a>{editing&&<button onClick={()=>removeProduct(p.id)}>삭제</button>}</article>)}</div></section>
    {editing&&<aside className="editor"><div className="editor-title"><div><p className="section-kicker">ITEM MANAGER</p><h2>추천 아이템 등록</h2></div><button onClick={()=>setEditing(false)}>×</button></div><form onSubmit={addProduct}><label>상품명<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="예: 아침을 깨우는 텀블러"/></label><label>한 줄 소개<input required value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="추천 이유를 짧게 적어주세요"/></label><label>상품 이미지 URL<input required type="url" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} placeholder="https://..."/></label><label>판매 상품페이지 URL<input required type="url" value={form.productUrl} onChange={e=>setForm({...form,productUrl:e.target.value})} placeholder="https://..."/></label><label>추천 태그<input value={form.tag} onChange={e=>setForm({...form,tag:e.target.value})}/></label><button className="submit" type="submit">{saved?'등록했어요 ✓':'추천 아이템 등록하기'}</button><p>등록한 상품은 현재 기기에 저장됩니다.</p></form></aside>}
    <footer><div className="profile-mark mini">가치<br/>똑똑<span>!</span></div><p>작지만 좋은 가치가 더 멀리 닿도록.</p><small>© VALUE SMART. ALL RIGHTS RESERVED.</small></footer>
  </main>;
}
